In [3]:
import pandas as pd

In [1]:
#Padndas DataFrame and Sries
#Series:- A pandas series is one-dimensional arrays-like object that can hold any data type.It is similar to a column in a table
import pandas as pd
data=[1,2,3,4,5]
series_pd=pd.Series(data)
print(series_pd)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
#create a Series form dictonary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [3]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [4]:
## Dataframe

## create a dataframe from a duictionary of list

data={
    'Name':['Krish','John','Jack'],
    'Age':[25,30,45],
    'City':['Banglore','New York','Florida']
}

df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  Krish   25  Banglore
1   John   30  New York
2   Jack   45   Florida
<class 'pandas.DataFrame'>

In [23]:
#create a Data Frame from a list of dictionarires
data=[
    {'Name':'Krish','Age': 25,'City':'Banglore'},
    {'Name':'Jack','Age': 30,'City':'New York'},
    {'Name':'John','Age': 45,'City':'Florida'},
    {'Name':'Bappy','Age': 25,'City':'Banglore'}

]
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  Krish   25  Banglore
1   Jack   30  New York
2   John   45   Florida
3  Bappy   25  Banglore
<class 'pandas.DataFrame'>

In [22]:
# read csv file 
df1=pd.read_csv('customers-100.csv')
df1.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [8]:
df.tail(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [9]:
data

[{'Name': 'Krish', 'Age': 25, 'City': 'Banglore'},
 {'Name': 'Jack', 'Age': 30, 'City': 'New York'},
 {'Name': 'John', 'Age': 45, 'City': 'Florida'},
 {'Name': 'Bappy', 'Age': 25, 'City': 'Banglore'}]

In [25]:
df

    Name  Age      City
0  Krish   25  Banglore
1   Jack   30  New York
2   John   45   Florida
3  Bappy   25  Banglore

In [12]:
type(df['First Name'])

pandas.Series

In [29]:
df.loc[0]

Name       Krish
Age           25
City    Banglore
Name: 0, dtype: object

In [26]:
df.iloc[1]

Name        Jack
Age           30
City    New York
Name: 1, dtype: object

In [27]:
# Accessing specified element
df['Name']

0    Krish
1     Jack
2     John
3    Bappy
Name: Name, dtype: str

In [28]:
df.at[2,'Name']

'John'

In [30]:
df.iat[2,2]

'Florida'

In [34]:
 # data Manipulation with dataframe
df

    Name  Age      City
0  Krish   25  Banglore
1   Jack   30  New York
2   John   45   Florida
3  Bappy   25  Banglore

In [36]:
## add salary on df
df['Salary']=[50000,60000,70000,80000]
df

    Name  Age      City  Salary
0  Krish   25  Banglore   50000
1   Jack   30  New York   60000
2   John   45   Florida   70000
3  Bappy   25  Banglore   80000

In [40]:
## Remove a column
df.drop('Salary',axis=1,inplace=True)

In [41]:
df

    Name  Age      City
0  Krish   25  Banglore
1   Jack   30  New York
2   John   45   Florida
3  Bappy   25  Banglore

In [42]:
## Add age to the column
df['Age']=df['Age']+1

In [43]:
df

    Name  Age      City
0  Krish   26  Banglore
1   Jack   31  New York
2   John   46   Florida
3  Bappy   26  Banglore

In [45]:
## Display the dtaa type at each column
print("data type:\n",df.dtypes)


#Describe the Dataframe
print("statical summary:\n",df.describe())

##group by a column and perform an aggregation

# grouped=df.groupby('Category')['Value'].mean()
# print("Mean value by catageory:\n",grouped)

data type:
 Name      str
Age     int64
City      str
dtype: object
statical summary:
              Age
count   4.000000
mean   32.250000
std     9.464847
min    26.000000
25%    26.000000
50%    28.500000
75%    34.750000
max    46.000000

In [46]:
df.describe()

             Age
count   4.000000
mean   32.250000
std     9.464847
min    26.000000
25%    26.000000
50%    28.500000
75%    34.750000
max    46.000000